Gen I and II Support
FlagBrew/PKSM-Core pull request #4
Opened 2021-09-10 18:53 UTC by SNBeast

- [x] Test
- [ ] Test better by having a GUI to use

2021-09-11 23:08 UTC, piepie62 requested changes
Thanks for working on this! Most of it seems fine, just a few issues that'll need to get ironed out.

2021-09-11 23:08 UTC, piepie62 commented on include/utils/utils.hpp
> +    std::string getTradeOT(pksm::Language lang);
Why is this in the StringUtils namespace?

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +        pk2->statExperience(Stat::HP, ev(Stat::HP));
These are probably supposed to be pk2->statExperience(<stat>, statExperience(<stat>)). That said, the "statExperience" model will be discussed in the Discord first; I'm not sure whether or not I like the way this is handled.

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +                pk7->abilityNumber(1);
These two should be merged into setAbility(0)

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +                pk7->abilityNumber(4);
These two should be merged into setAbility(2)

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +        // TODO
Get this done, please

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +                // TODO
Get this done, please

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +        return Nature{u8(experience() % 25)};
*Really*? That seems... terrifying

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +        while (experience() >= expTable(i, xpType) && ++i < 100)
Isn't this the generation where you can have level 101+ Pokémon? Should we handle that if so?

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK1.cpp
> +    int PK1::boxLevel() const
Not sure I like this; it should probably be directly accessed via `level()` with that secondarily setting experience. Feel free to convince me otherwise

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK2.cpp
> +        pk1->statExperience(Stat::HP, ev(Stat::HP));
Same as for PK1

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK2.cpp
> +        // TODO
Do this, please

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK2.cpp
> +        // TODO
Do this, please

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK2.cpp
> +        while (experience() >= expTable(i, xpType) && ++i < 100)
Or was it G2 that could have level 100+? Both of them, perhaps?

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PK3.cpp
> +        pk2->move(0, move(0));
These need to be checked so that it can't transfer back a set of non-existent moves

2021-09-11 23:08 UTC, piepie62 commented on source/pkx/PKX.cpp
> +                    boxlen = PK3::BOX_LENGTH;
These should all be PARTY_LENGTH; the point of this function is to clone the current Pokémon as a party Pokémon

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav.cpp
> +        u32 versionAndLanguage = Sav2::getVersion(dt);
Should be changed to follow API suggestion about this function

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav.cpp
> +                return pk.convertToG1(*this);
My understanding is that this doesn't handle cross-language transfer. Should it?

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +    u32 Sav2::getVersion(std::shared_ptr<u8[]> dt)
This function should return an std::tuple<GameVersion, Language, bool>

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +    Sav1::Sav1(std::shared_ptr<u8[]> data) : Sav1(data, 0x8000) {}
My first thought is that this constructor shouldn't exist. Why does it currently?

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +    u8 Sav1::calculateChecksum(const u8* data, size_t len)
Most of this logic should be extracted to a pksm::crypto function

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +            data[japanese ? 0x2CA4 : 0x2CF1] = 59;  // frame count
I'm not sure I like these ternary operators throughout the file. Perhaps Sav1Int and Sav1JP classes? If not, perhaps most offsets should be calculated off more offset variables

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +    // why did they use BCD
BCD translation seems like it be generalized somewhere else. pksm::crypto doesn't feel right, but perhaps in (Big|Little)Endian?

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +        u8 buffer[PK1Length()] = {0x01, data[partyOffset(slot)], 0xFF};
No variable-length arrays! Either use the largest length for the buffer or dynamically allocate it (I'd suggest the former, but might be convinced that the latter is better)

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +        u8 buffer[PK1Length()] = {0x01, data[boxOffset(box, slot)], 0xFF};
Same here with VLAs

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +        if (pk.generation() == Generation::ONE && ((pk.language() != Language::JPN) ^ (language() == Language::JPN)))
Second condition group should be `((pk.language() == Language::JPN) == (language() == Language::JPN))`. Also, this function should support swapping languages between JPN and INT unless you can convince me that it's completely infeasible.

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav1.cpp
> +    void Sav1::trade(PKX& pk, const Date& date) const {}
This *probably* shouldn't be a noop

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +    u16 Sav2::calculateChecksum(u8* start, const u8* end)
A: this isn't how constness on pointers works. B: this logic should be extracted to a pksm::crypto function. Not quite certain what to call this, though: it's possible that `pksm::crypto::sum32` should be changed to a template with parameters that specify its read and return sizes

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +        if (((lang == Language::JPN) ^ (v != Language::JPN)) &&
Condition should be `((lang == Language::JPN) == (v == Language::JPN)) && ((lang == Language::KOR) == (v == Language::KOR))`.

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +        u8 buffer[PK2Length()] = {0x01, data[OFS_PARTY + 1 + slot], 0xFF};
No VLAs again

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +        u8 buffer[PK2Length()] = {0x01, data[boxStart(box) + 1 + slot], 0xFF};
No VLAs again

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +        if (pk.generation() == Generation::TWO &&
Same as G1 Pokémon setting: unless you can convince me it's infeasible, I want Japanese-Korean-international transfer to work. If you can't, condition should use boolean operators instead of bitwise ones again.

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +                trade(*pk2);
Doesn't seem to handle language transfer properly

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +    void Sav2::trade(PKX& pk, const Date& date) const {}
Probably shouldn't be a noop

2021-09-11 23:08 UTC, piepie62 commented on source/sav/Sav2.cpp
> +    int Sav2::maxSlot() const { return maxBoxes() * /*(japanese ? 30 : 20)*/ 30; }
Change that to what it should be, UI will be modified to work properly. In general for the future, just pretend the UI works properly for what you want; if I need to change these assumptions to make it easier on the UI stuff, I'll do that when I build it.

2021-09-11 23:08 UTC, piepie62 commented on source/utils/g1text.hpp
> +    std::unordered_map<u8, char16_t> G1_EN = {{0x50, u'\0'}, {0x5D, tradeOTChar},
This should be a pair of constexpr arrays, not an unordered_map

2021-09-11 23:08 UTC, piepie62 commented on source/utils/g1text.hpp
> +    std::unordered_map<u8, char16_t> G1_JP = {{0x05, u'ガ'}, {0x06, u'ギ'}, {0x07, u'グ'},
Same here

2021-09-11 23:08 UTC, piepie62 commented on source/utils/g2text.hpp
> +namespace pksm::internal
This file and corresponding methods seem to be a mess. I'll need to discuss them with you.

2021-09-11 23:42 UTC, SNBeast commented on source/pkx/PK1.cpp
> +        return Nature{u8(experience() % 25)};
Yep. From Bulbapedia:
> A transferred Pokémon's nature is that nature whose index number corresponds to the Pokémon's experience modulo 25.

2021-09-11 23:52 UTC, SNBeast commented on source/sav/Sav1.cpp
> +    void Sav1::trade(PKX& pk, const Date& date) const {}
This is, like in Gen III.

2021-09-11 23:58 UTC, SNBeast commented on include/utils/utils.hpp
> +    std::string getTradeOT(pksm::Language lang);
It's exclusively used by functions in that namespace, and is a utility function that returns a string.

2021-09-12 14:16 UTC, SNBeast commented on source/sav/Sav1.cpp
> +    // why did they use BCD
Not that I could find. You want it elsewhere?

2021-09-12 14:33 UTC, SNBeast commented on source/sav/Sav2.cpp
> +    void Sav2::trade(PKX& pk, const Date& date) const {}
It is a noop. Eggs have their met location set to where they hatch when they hatch.

2021-09-12 16:27 UTC, SNBeast commented on source/sav/Sav2.cpp
> +    u16 Sav2::calculateChecksum(u8* start, const u8* end)
I'm thinking `bytewiseSum16`.

2021-09-12 18:00 UTC, SNBeast commented on source/pkx/PK1.cpp
> +    int PK1::boxLevel() const
I don't agree, as this value doesn't update while in the party afaik.

2021-09-15 20:14 UTC, SNBeast commented on source/pkx/PK1.cpp
> +        while (experience() >= expTable(i, xpType) && ++i < 100)
Resolved elsewhere: decided against

2021-09-15 20:14 UTC, SNBeast commented on source/pkx/PK2.cpp
> +        while (experience() >= expTable(i, xpType) && ++i < 100)
Resolved elsewhere: decided against

2021-09-21 23:19 UTC, piepie62 requested changes

2021-09-21 23:19 UTC, piepie62 commented on include/utils/utils.hpp
> +namespace NumberFormatUtils
I actually meant for this to be in the LittleEndian/BigEndian namespaces respectively. Could you move these there?

2021-09-21 23:19 UTC, piepie62 commented on include/utils/utils.hpp
> +    constexpr std::array<u8, arrayLength> UIntegerToBigEndianBCD(T src)
This should have an overload that writes directly out to a u8 pointer (still with an arrayLength template parameter); look at the way that LittleEndian::convertFrom with an array works for an example of what I would prefer

2021-09-21 23:19 UTC, piepie62 commented on source/sav/Sav1.cpp
> +        std::array<u8, 3> bcd = NumberFormatUtils::UIntegerToBigEndianBCD<u32, 3>(v);
Use the change to this function requested to write directly instead of having a temporary

2021-09-21 23:19 UTC, piepie62 commented on include/utils/utils.hpp
> +    constexpr T BigEndianBCDtoUInteger(const u8* src, size_t arrayLength)
arrayLength should be a template parameter

2022-07-05 13:02 UTC, Octoham commented
I'm glad this is being worked on!
That being said, I'd love to contribute to the gen 1 and 2 support. What is left to complete?

2022-09-12 02:26 UTC, SNBeast commented
Marked as mergeable.

2022-09-12 16:31 UTC, merged